/**
 * Turns a built frontend directory into a TypeScript module of `type: "file"`
 * imports, which `bun build --compile` embeds in the binary. The alternative,
 * base64 string literals, inflates the source by a third and costs a decode on
 * every start.
 *
 *   bun run tools/gen-assets.ts --web ../../dist --out src/assets.gen.ts
 */
import { existsSync, mkdirSync, readdirSync, statSync, writeFileSync } from "node:fs";
import { dirname, join, relative, resolve } from "node:path";

function argValue(flag: string, fallback: string): string {
  const index = process.argv.indexOf(flag);
  return index >= 0 && process.argv[index + 1] ? process.argv[index + 1]! : fallback;
}

const here = resolve(import.meta.dir, "..");
const webDir = resolve(here, argValue("--web", "../../dist"));
const outFile = resolve(here, argValue("--out", "src/assets.gen.ts"));

function walk(dir: string, base = dir): string[] {
  if (!existsSync(dir)) return [];
  const out: string[] = [];
  for (const entry of readdirSync(dir).sort()) {
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) out.push(...walk(full, base));
    else out.push(relative(base, full));
  }
  return out;
}

const files = walk(webDir).filter((file) => !file.startsWith("."));
mkdirSync(dirname(outFile), { recursive: true });

if (files.length === 0) {
  writeFileSync(
    outFile,
    [
      "// GENERATED by tools/gen-assets.ts - do not edit.",
      "// No frontend build was found, so the binary ships with the built-in status page only.",
      "export const WEB_ASSETS: Record<string, string> = {};",
      'export const WEB_BUILD_ID = "none";',
      "",
    ].join("\n"),
  );
  console.log(`no files under ${webDir}; wrote an empty asset map`);
  process.exit(0);
}

const imports: string[] = [];
const entries: string[] = [];
files.forEach((file, index) => {
  // Import specifiers are relative to the generated file, and always POSIX.
  const specifier = relative(dirname(outFile), join(webDir, file)).split(/[\\/]/).join("/");
  imports.push(`import f${index} from "${specifier.startsWith(".") ? specifier : `./${specifier}`}" with { type: "file" };`);
  entries.push(`  "/${file.split(/[\\/]/).join("/")}": f${index},`);
});

const buildId = files
  .map((file) => `${file}:${statSync(join(webDir, file)).size}`)
  .join("|");
const hash = new Bun.CryptoHasher("sha256").update(buildId).digest("hex").slice(0, 12);

writeFileSync(
  outFile,
  [
    "// GENERATED by tools/gen-assets.ts - do not edit.",
    `// Source: ${relative(here, webDir)} (${files.length} files)`,
    ...imports,
    "",
    "export const WEB_ASSETS: Record<string, string> = {",
    ...entries,
    "};",
    "",
    `export const WEB_BUILD_ID = ${JSON.stringify(hash)};`,
    "",
  ].join("\n"),
);

console.log(`embedded ${files.length} files from ${webDir} -> ${relative(here, outFile)} (build ${hash})`);
