/**
 * Embed the bundled skill into the compiled binary.
 *
 * `bun build --compile` puts the program in a virtual filesystem, so
 * `import.meta.dir` is not a real directory and the skill's python cannot be found
 * next to the executable. Worse, that python runs as a subprocess and is read by
 * pip, and neither can see the virtual filesystem at all. So the files are embedded
 * here and written to a real directory on first run.
 *
 * `with { type: "file" }` only accepts literal paths, hence a generated module.
 *
 *   bun run tools/gen-skill-assets.ts     # -> src/skill-assets.generated.ts
 */
import { readdirSync, statSync, writeFileSync } from "node:fs";
import { join, relative, resolve } from "node:path";

const ROOT = resolve(import.meta.dir, "..");
const SKILL = join(ROOT, "skills", "omnisci");
const OUT = join(ROOT, "src", "skill-assets.generated.ts");

function walk(dir: string, acc: string[] = []): string[] {
  for (const name of readdirSync(dir)) {
    const full = join(dir, name);
    if (full.includes("__pycache__")) continue;
    if (statSync(full).isDirectory()) walk(full, acc);
    else acc.push(full);
  }
  return acc;
}

let files: string[];
try {
  files = walk(SKILL).sort();
} catch {
  console.error(`没有 ${SKILL}`);
  process.exit(1);
}
if (!files.some((f) => f.endsWith("gate_cli.py"))) {
  console.error(`${SKILL} 里没有 gate_cli.py，skill 不完整`);
  process.exit(1);
}

const lines = [
  "// GENERATED by tools/gen-skill-assets.ts. 不要手改，构建时会覆盖。",
  "// 每条 import 都被 `bun build --compile` 嵌进二进制，所以发行版就是一个文件。",
  "",
];
const entries: string[] = [];
files.forEach((full, i) => {
  const rel = relative(SKILL, full).split("\\").join("/");
  lines.push(`import s${i} from "../skills/omnisci/${rel}" with { type: "file" };`);
  entries.push(`  ${JSON.stringify(rel)}: s${i},`);
});

lines.push("");
lines.push("/** skill 内的相对路径 -> 嵌入文件路径。落盘之后才可用。 */");
lines.push("export const SKILL_FILES: Record<string, string> = {");
lines.push(...entries, "};", "");

writeFileSync(OUT, lines.join("\n"), "utf-8");
const bytes = files.reduce((n, f) => n + statSync(f).size, 0);
console.log(`embedded ${files.length} skill files (${(bytes / 1024).toFixed(0)} KB) -> ${relative(ROOT, OUT)}`);
