/**
 * 把 vite 的构建产物变成一个可以被 `bun build --compile` 嵌进二进制的模块。
 *
 * 为什么要生成：`with { type: "file" }` 只接受**字面量**路径，而 vite 的产物名带
 * 内容哈希，编译期才知道。所以构建完扫一遍 dist/，把每个文件写成一条静态 import。
 *
 *   bun run tools/gen-assets.ts        # 读 dist/，写 launcher/assets.generated.ts
 */
import { readdirSync, statSync, writeFileSync } from "node:fs";
import { join, relative, resolve } from "node:path";

const ROOT = resolve(import.meta.dir, "..");
const DIST = join(ROOT, "dist");
const OUT = join(ROOT, "launcher", "assets.generated.ts");

const MIME: Record<string, string> = {
  ".html": "text/html; charset=utf-8",
  ".js": "text/javascript; charset=utf-8",
  ".css": "text/css; charset=utf-8",
  ".json": "application/json; charset=utf-8",
  ".svg": "image/svg+xml",
  ".png": "image/png",
  ".jpg": "image/jpeg",
  ".jpeg": "image/jpeg",
  ".webp": "image/webp",
  ".ico": "image/x-icon",
  ".woff2": "font/woff2",
  ".woff": "font/woff",
  ".ttf": "font/ttf",
  ".pdf": "application/pdf",
  ".txt": "text/plain; charset=utf-8",
  ".map": "application/json; charset=utf-8",
};

function walk(dir: string, acc: string[] = []): string[] {
  for (const name of readdirSync(dir)) {
    const full = join(dir, name);
    if (statSync(full).isDirectory()) walk(full, acc);
    else acc.push(full);
  }
  return acc;
}

const SKILL = resolve(ROOT, "..", "cli", "skills", "omnisci");

let files: string[];
try {
  files = walk(DIST).sort();
} catch {
  console.error(`没有 ${DIST}，先跑 vite build`);
  process.exit(1);
}
if (!files.some((f) => f.endsWith("index.html"))) {
  console.error(`${DIST} 里没有 index.html，构建产物不完整`);
  process.exit(1);
}

let skillFiles: string[];
try {
  skillFiles = walk(SKILL).filter((f) => !f.includes("__pycache__")).sort();
} catch {
  console.error(`没有 ${SKILL}`);
  process.exit(1);
}
if (!skillFiles.some((f) => f.endsWith("gate_cli.py"))) {
  console.error(`${SKILL} 里没有 gate_cli.py，skill 不完整`);
  process.exit(1);
}

const lines: string[] = [
  "// GENERATED by tools/gen-assets.ts. 不要手改，重新构建会覆盖。",
  "// 每一条 import 都会被 `bun build --compile` 嵌进二进制，所以桌面版不依赖 dist/ 目录。",
  "",
];
const assetEntries: string[] = [];
const skillEntries: string[] = [];

files.forEach((full, i) => {
  const rel = relative(DIST, full).split("\\").join("/");
  const ext = rel.slice(rel.lastIndexOf("."));
  lines.push(`import a${i} from "../dist/${rel}" with { type: "file" };`);
    // Bun 给 .html/.json 单独的类型（HTMLBundle、解析后的对象），而这里要的一律是
  // 内嵌文件的路径字符串，所以统一断言一次。
  assetEntries.push(`  "/${rel}": { path: a${i} as unknown as string, type: ${JSON.stringify(MIME[ext] ?? "application/octet-stream")} },`);
});

// skill 是 python，要被子进程执行，也要被 pip 读，所以不能停在 Bun 的虚拟文件系统里。
// 这里只负责嵌进去，落盘在 launcher/main.ts 的 installSkill()。
skillFiles.forEach((full, i) => {
  const rel = relative(SKILL, full).split("\\").join("/");
  lines.push(`import s${i} from "../../cli/skills/omnisci/${rel}" with { type: "file" };`);
  skillEntries.push(`  ${JSON.stringify(rel)}: s${i},`);
});

lines.push("");
lines.push("export interface EmbeddedAsset { path: string; type: string }");
lines.push("");
lines.push("export const ASSETS: Record<string, EmbeddedAsset> = {");
lines.push(...assetEntries);
lines.push("};");
lines.push("");
lines.push("/** skill 内的相对路径 -> 嵌入文件路径。落盘后才可用。 */");
lines.push("export const SKILL_FILES: Record<string, string> = {");
lines.push(...skillEntries);
lines.push("};");
lines.push("");

writeFileSync(OUT, lines.join("\n"), "utf-8");
const bytes = [...files, ...skillFiles].reduce((n, f) => n + statSync(f).size, 0);
console.log(
  `embedded ${files.length} web files + ${skillFiles.length} skill files `
  + `(${(bytes / 1024 / 1024).toFixed(1)} MB) -> ${relative(ROOT, OUT)}`,
);
