// GENERATED by tools/gen-skill-assets.ts. 不要手改，构建时会覆盖。
// 每条 import 都被 `bun build --compile` 嵌进二进制，所以发行版就是一个文件。

import s0 from "../skills/omnisci/SKILL.md" with { type: "file" };
import s1 from "../skills/omnisci/bin/case_cli.py" with { type: "file" };
import s2 from "../skills/omnisci/bin/evidence_cli.py" with { type: "file" };
import s3 from "../skills/omnisci/bin/gate_cli.py" with { type: "file" };
import s4 from "../skills/omnisci/bin/hostbridge.py" with { type: "file" };
import s5 from "../skills/omnisci/bin/lit_cli.py" with { type: "file" };
import s6 from "../skills/omnisci/bin/paper_cli.py" with { type: "file" };
import s7 from "../skills/omnisci/bin/vendor/agentic.py" with { type: "file" };
import s8 from "../skills/omnisci/bin/vendor/evidence.py" with { type: "file" };
import s9 from "../skills/omnisci/bin/vendor/figtools.py" with { type: "file" };
import s10 from "../skills/omnisci/bin/vendor/paper.py" with { type: "file" };
import s11 from "../skills/omnisci/bin/vendor/paper_specs.py" with { type: "file" };
import s12 from "../skills/omnisci/bin/vendor/paperlint.py" with { type: "file" };
import s13 from "../skills/omnisci/bin/vendor/paradigms.py" with { type: "file" };
import s14 from "../skills/omnisci/bin/vendor/venue_styles.py" with { type: "file" };
import s15 from "../skills/omnisci/bin/vendor/writer.py" with { type: "file" };
import s16 from "../skills/omnisci/requirements.txt" with { type: "file" };

/** skill 内的相对路径 -> 嵌入文件路径。落盘之后才可用。 */
export const SKILL_FILES: Record<string, string> = {
  "SKILL.md": s0,
  "bin/case_cli.py": s1,
  "bin/evidence_cli.py": s2,
  "bin/gate_cli.py": s3,
  "bin/hostbridge.py": s4,
  "bin/lit_cli.py": s5,
  "bin/paper_cli.py": s6,
  "bin/vendor/agentic.py": s7,
  "bin/vendor/evidence.py": s8,
  "bin/vendor/figtools.py": s9,
  "bin/vendor/paper.py": s10,
  "bin/vendor/paper_specs.py": s11,
  "bin/vendor/paperlint.py": s12,
  "bin/vendor/paradigms.py": s13,
  "bin/vendor/venue_styles.py": s14,
  "bin/vendor/writer.py": s15,
  "requirements.txt": s16,
};
